name: petwalk
description: 반려견 산책 기록 및 산책로 추천 앱
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # 위치 / GPS
  geolocator: ^13.0.1

  # 지도 (개발 단계: OSM 타일. 추후 네이버/카카오 SDK로 교체 예정)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # 로컬 저장
  sqflite: ^2.3.3
  path: ^1.9.0

  # 상태관리
  provider: ^6.1.2
  sqflite_common_ffi_web: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite_common_ffi: ^2.4.2+1

flutter:
  uses-material-design: true
